# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false
after_success:
  # build docs
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("StructDualDynProg")); include(joinpath("docs", "make.jl"))'
