name = "StochOptInterface"
uuid = "ddbffdd9-5b1a-5f20-b6eb-597a58a751db"
authors = ["JuliaStochOpt"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
DocStringExtensions = "0.8"
LightGraphs = "1.3"
TimerOutputs = "0.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
