name = "StochOptInterface"
uuid = "ddbffdd9-5b1a-5f20-b6eb-597a58a751db"
authors = ["JuliaStochOpt"]
version = "0.2.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
DocStringExtensions = "0.9"
Graphs = "1"
TimerOutputs = "0.5"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
